/* auto-generated by NAPI-RS */
/* eslint-disable */
/** * IpToAsn class provides IP to ASN lookup functionality with automatic database updates.
 */
export declare class IpToAsn {
  /** * Creates a new IpToAsn instance.
   * @param url - Database URL (HTTP/HTTPS or file://)
   * @param cache_dir - Directory for caching downloaded databases
   */
  constructor(url: string, cacheDir: string)
  /** * Load the database
   * @returns Promise that resolves when loading is complete
   */
  load(): Promise<void>
  /** * Look up an IP address
   * @param ip - IP address to look up (IPv4 or IPv6)
   * @returns ASN information or null if not found
   */
  lookup(ip: string): AsnResult
  /** * Get database statistics
   * @returns Statistics including record count and last update time
   */
  stats(): DatabaseStats
  /** * Start automatic database updates
   * @param interval_minutes - How often to check for updates (in minutes)
   */
  startAutoUpdate(intervalMinutes: number): Promise<void>
  /** * Stop automatic database updates
   * @returns Promise that resolves when auto-update is stopped
   */
  stopAutoUpdate(): void
  /** * Force an immediate database update check
   * @returns true if database was updated, false if already up-to-date
   */
  forceUpdate(): Promise<boolean>
}

/** * ASN lookup result returned to Node.js
 * @property {string} ip - The queried IP address
 * @property {boolean} announced - Whether the IP is announced
 * @property {string | null} first_ip - First IP in the ASN range (null if not announced)
 * @property {string | null} last_ip - Last IP in the ASN range (null if not announced)
 * @property {number | null} as_number - ASN number (null if not announced)
 * @property {string | null} as_country_code - ASN country code (null if not announced)
 * @property {string | null} as_description - ASN description (null if not announced)
 */
export interface AsnResult {
  ip: string
  announced: boolean
  firstIp?: string
  lastIp?: string
  asNumber?: number
  asCountryCode?: string
  asDescription?: string
}

/** * Database statistics
 * @property {number} record_count - Number of records in the database
 * @property {number | null} last_update_timestamp - Timestamp of the last update (null if unknown)
 */
export interface DatabaseStats {
  recordCount: number
  lastUpdateTimestamp?: number
}

/** * Get the package version
 * @returns The current version of the iptoasn-node package
 */
export declare function getVersion(): string
